import json
from agentic_ai.agents.base_agent import BaseAgent
from agentic_ai.communication.message_schema import MessageType, Topic
from src.config.settings import PATHS
import os


class BusinessAnalyst2Agent(BaseAgent):
    def __init__(self, message_bus, project_state, anthropic_client):
        tools = [
            {
                "name": "draft_stakeholder_update",
                "description": "Draft an executive stakeholder update for the current phase",
                "input_schema": {
                    "type": "object",
                    "properties": {
                        "phase":   {"type": "string"},
                        "summary": {"type": "string"},
                    },
                    "required": ["phase", "summary"],
                },
            },
            {
                "name": "create_requirements_doc",
                "description": "Create a business requirements document",
                "input_schema": {
                    "type": "object",
                    "properties": {
                        "requirements": {"type": "array", "items": {"type": "string"}},
                        "title":        {"type": "string"},
                    },
                    "required": ["requirements", "title"],
                },
            },
            {
                "name": "log_stakeholder_feedback",
                "description": "Record stakeholder feedback",
                "input_schema": {
                    "type": "object",
                    "properties": {
                        "stakeholder": {"type": "string"},
                        "feedback":    {"type": "string"},
                    },
                    "required": ["stakeholder", "feedback"],
                },
            },
            {
                "name": "notify_business_lead",
                "description": "Notify Business Lead of completed work",
                "input_schema": {
                    "type": "object",
                    "properties": {"summary": {"type": "string"}},
                    "required": ["summary"],
                },
            },
        ]
        super().__init__(
            agent_id="business_analyst_2",
            role="Business Analyst 2 — Stakeholder Communication",
            topics=[Topic.BUSINESS, Topic.MANAGEMENT],
            message_bus=message_bus,
            project_state=project_state,
            anthropic_client=anthropic_client,
            tools=tools,
        )
        self.system_prompt = (
            "You are Business Analyst 2, specializing in stakeholder communication and requirements. "
            "Phase 5: Draft a concise executive stakeholder update summarizing the project's outcomes "
            "(segments found, top recommendations, KPI impacts), create a requirements document, "
            "and notify Business Lead when done. "
            "Be clear, concise and business-focused (no technical jargon)."
        )

    async def _handle_task(self, message):
        payload_str = json.dumps(message.payload)
        snap = self.project_state.snapshot()
        prompt = (
            f"Message from {message.from_agent} [{message.message_type}]:\n{payload_str}\n"
            f"Project state: {json.dumps(snap)}\n"
            "Draft stakeholder update, create requirements doc, log any feedback, then notify Business Lead."
        )
        await self._run_tool_loop(prompt)

    async def _tool_draft_stakeholder_update(self, phase: str, summary: str) -> str:
        os.makedirs(PATHS["reports"], exist_ok=True)
        path = os.path.join(PATHS["reports"], f"stakeholder_update_{phase}.md")
        content = (
            f"# Stakeholder Update — {phase}\n\n"
            f"{summary}\n\n"
            "_Generated by Business Analyst 2_"
        )
        with open(path, "w") as f:
            f.write(content)
        return json.dumps({"status": "ok", "path": path})

    async def _tool_create_requirements_doc(self, requirements: list[str], title: str) -> str:
        os.makedirs(PATHS["reports"], exist_ok=True)
        path = os.path.join(PATHS["reports"], "business_requirements.md")
        lines = [f"# {title}\n"]
        for i, req in enumerate(requirements, 1):
            lines.append(f"{i}. {req}")
        with open(path, "w") as f:
            f.write("\n".join(lines))
        return json.dumps({"status": "ok", "path": path})

    async def _tool_log_stakeholder_feedback(self, stakeholder: str, feedback: str) -> str:
        entry = {"stakeholder": stakeholder, "feedback": feedback}
        current = self.project_state.feedback_log
        current.append(entry)
        await self.project_state.update("feedback_log", current)
        return json.dumps({"status": "ok", "entry": entry})

    async def _tool_notify_business_lead(self, summary: str) -> str:
        await self.send_message(
            to="business_lead",
            topic=Topic.BUSINESS,
            message_type=MessageType.STATUS_UPDATE,
            payload={"summary": summary, "agent": self.agent_id},
        )
        return f"Business Lead notified: {summary}"
